In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
import pickle

In [2]:
df = pd.read_csv('Churn_Modelling.csv')

In [3]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
df=df.drop(columns=['RowNumber','CustomerId','Surname'])

In [5]:
##Encode categorical variables
label_encoder_gender = LabelEncoder()
df['Gender']=label_encoder_gender.fit_transform(df['Gender'])

In [6]:
onehotencoder_geography = OneHotEncoder(sparse_output=False)
geo_encoder = onehotencoder_geography.fit_transform(df[['Geography']])
geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [7]:
onehotencoder_geography.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [8]:
geo_encoded_df=pd.DataFrame(geo_encoder,columns=onehotencoder_geography.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [9]:
##combine one hot encoded columns with the original data
df=pd.concat([df.drop('Geography',axis=1),geo_encoded_df],axis=1)
df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [10]:
##split the data into features and target
X = df.drop(['EstimatedSalary'],axis=1)
y = df['EstimatedSalary']

In [11]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)

##scale these features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [12]:
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehotencoder_geography.pkl','wb') as file:
    pickle.dump(onehotencoder_geography,file)

with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

In [13]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [14]:
##Build the model
model = Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)), ##HL1 CONNECTED WITH INPUT LAYER
    Dense(32,activation='relu'), ##HL2
    Dense(1) ##output layer
])

/opt/miniconda3/lib/python3.13/site-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [15]:
## compile the model
model.compile(optimizer="adam",loss='mean_absolute_error',metrics=['mae'])
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
## set up the tensorboard
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir,histogram_freq=1)

In [17]:
## setup earlystopping
early_stopping_callback = EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [18]:
## Train the model
history = model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100632.9766 - mae: 100632.9766 - val_loss: 98211.0938 - val_mae: 98211.0938
Epoch 2/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 917us/step - loss: 100085.6250 - mae: 100085.6250 - val_loss: 97075.8750 - val_mae: 97075.8750
Epoch 3/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 98088.2656 - mae: 98088.2656 - val_loss: 94097.4766 - val_mae: 94097.4766
Epoch 4/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 94023.8203 - mae: 94023.8203 - val_loss: 88919.8125 - val_mae: 88919.8125
Epoch 5/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 87849.5000 - mae: 87849.5000 - val_loss: 81943.7578 - val_mae: 81943.7578
Epoch 6/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 80082.0312 - mae: 80082.0312 - val_loss: 74006.2734 - val_mae: 74006.2734
Epoch 7/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 961us/step - loss: 71795.5156 - mae: 71795.5156 - val_loss: 66328.4375 - val_mae: 66328.4375
Epoch 8/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 64221.3320 - mae: 64221.3320 - val_loss: 59948.8320 - val_mae: 59948.8320
Epoch 9/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 969us/step - loss: 58227.7500 - mae: 58227.7500 - val_loss: 55339.4883 - val_mae: 55339.4883
Epoch 10/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 973us/step - loss: 54267.1172 - mae: 54267.1172 - val_loss: 52706.9688 - val_mae: 52706.9688
Epoch 11/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 926us/step - loss: 52080.4102 - mae: 52080.4102 - val_loss: 51513.3555 - val_mae: 51513.3555
Epoch 12/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - loss: 51024.4648 - mae: 51024.4648 - val_loss: 50985.9180 - val_mae: 50985.9180
Epoch 13/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 966us/step - loss: 50574.9531 - mae: 50574.9531 - val_loss: 50799.6602 - val_mae: 50799.6602
Epoch 14/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50379.0117 - mae: 50379.0117 - val_loss: 50726.3047 - val_mae: 50726.3047
Epoch 15/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 967us/step - loss: 50264.3125 - mae: 50264.3125 - val_loss: 50674.6875 - val_mae: 50674.6875
Epoch 16/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 927us/step - loss: 50186.1875 - mae: 50186.1875 - val_loss: 50628.1445 - val_mae: 50628.1445
Epoch 17/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 933us/step - loss: 50128.5117 - mae: 50128.5117 - val_loss: 50593.7969 - val_mae: 50593.7969
Epoch 18/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - loss: 50081.7422 - mae: 50081.7422 - val_loss: 50550.4180 - val_mae: 50550.4180
Epoch 19/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - loss: 50038.7422 - mae: 50038.7422 - val_loss: 50523.7812 - val_mae: 50523.7812
Epoch 20/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - loss: 50002.8203 - mae: 50002.8203 - val_loss: 50471.3359 - val_mae: 50471.3359
Epoch 21/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - loss: 49972.8828 - mae: 49972.8828 - val_loss: 50433.8828 - val_mae: 50433.8828
Epoch 22/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 933us/step - loss: 49940.5625 - mae: 49940.5625 - val_loss: 50408.4883 - val_mae: 50408.4883
Epoch 23/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - loss: 49914.3555 - mae: 49914.3555 - val_loss: 50391.2188 - val_mae: 50391.2188
Epoch 24/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - loss: 49889.0820 - mae: 49889.0820 - val_loss: 50365.2305 - val_mae: 50365.2305
Epoch 25/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step - loss: 49865.4844 - mae: 49865.4844 - val_loss: 50351.8047 - val_mae: 50351.8047
Epoch 26/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 958us/step - loss: 49844.9570 - mae: 49844.9570 - val_loss: 50315.5859 - val_mae: 50315.5859
Epoch 27/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - loss: 49825.4648 - mae: 49825.4648 - val_loss: 50302.2031 - val_mae: 50302.2031
Epoch 28/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 919us/step - loss: 49806.4219 - mae: 49806.4219 - val_loss: 50282.3516 - val_mae: 50282.3516
Epoch 29/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 935us/step - loss: 49789.1406 - mae: 49789.1406 - val_loss: 50259.1250 - val_mae: 50259.1250
Epoch 30/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - loss: 49773.6719 - mae: 49773.6719 - val_loss: 50238.2188 - val_mae: 50238.2188
Epoch 31/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - loss: 49757.4922 - mae: 49757.4922 - val_loss: 50226.1016 - val_mae: 50226.1016
Epoch 32/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 943us/step - loss: 49740.0820 - mae: 49740.0820 - val_loss: 50213.5781 - val_mae: 50213.5781
Epoch 33/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 917us/step - loss: 49724.9336 - mae: 49724.9336 - val_loss: 50201.7266 - val_mae: 50201.7266
Epoch 34/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step - loss: 49710.0234 - mae: 49710.0234 - val_loss: 50198.2969 - val_mae: 50198.2969
Epoch 35/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - loss: 49698.8086 - mae: 49698.8086 - val_loss: 50187.1406 - val_mae: 50187.1406
Epoch 36/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 931us/step - loss: 49689.2852 - mae: 49689.2852 - val_loss: 50179.7383 - val_mae: 50179.7383
Epoch 37/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49676.9961 - mae: 49676.9961 - val_loss: 50167.1641 - val_mae: 50167.1641
Epoch 38/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 946us/step - loss: 49666.8633 - mae: 49666.8633 - val_loss: 50163.2930 - val_mae: 50163.2930
Epoch 39/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - loss: 49653.1211 - mae: 49653.1211 - val_loss: 50149.6836 - val_mae: 50149.6836
Epoch 40/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - loss: 49647.5469 - mae: 49647.5469 - val_loss: 50159.2305 - val_mae: 50159.2305
Epoch 41/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 976us/step - loss: 49636.6523 - mae: 49636.6523 - val_loss: 50152.2539 - val_mae: 50152.2539
Epoch 42/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - loss: 49625.0000 - mae: 49625.0000 - val_loss: 50145.6328 - val_mae: 50145.6328
Epoch 43/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 919us/step - loss: 49615.0430 - mae: 49615.0430 - val_loss: 50144.3281 - val_mae: 50144.3281
Epoch 44/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - loss: 49606.0977 - mae: 49606.0977 - val_loss: 50138.9883 - val_mae: 50138.9883
Epoch 45/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - loss: 49599.1250 - mae: 49599.1250 - val_loss: 50137.3906 - val_mae: 50137.3906
Epoch 46/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - loss: 49590.4336 - mae: 49590.4336 - val_loss: 50133.6719 - val_mae: 50133.6719
Epoch 47/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step - loss: 49585.2031 - mae: 49585.2031 - val_loss: 50121.3125 - val_mae: 50121.3125
Epoch 48/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 911us/step - loss: 49578.9453 - mae: 49578.9453 - val_loss: 50122.3789 - val_mae: 50122.3789
Epoch 49/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49569.9492 - mae: 49569.9492 - val_loss: 50118.0430 - val_mae: 50118.0430
Epoch 50/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - loss: 49562.9883 - mae: 49562.9883 - val_loss: 50112.5234 - val_mae: 50112.5234
Epoch 51/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 947us/step - loss: 49563.2773 - mae: 49563.2773 - val_loss: 50111.2617 - val_mae: 50111.2617
Epoch 52/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 926us/step - loss: 49548.0391 - mae: 49548.0391 - val_loss: 50112.9102 - val_mae: 50112.9102
Epoch 53/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - loss: 49547.5234 - mae: 49547.5234 - val_loss: 50107.1914 - val_mae: 50107.1914
Epoch 54/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - loss: 49539.1602 - mae: 49539.1602 - val_loss: 50099.8125 - val_mae: 50099.8125
Epoch 55/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 895us/step - loss: 49533.0586 - mae: 49533.0586 - val_loss: 50104.4844 - val_mae: 50104.4844
Epoch 56/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 913us/step - loss: 49528.7578 - mae: 49528.7578 - val_loss: 50097.3555 - val_mae: 50097.3555
Epoch 57/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 968us/step - loss: 49519.1953 - mae: 49519.1953 - val_loss: 50098.6602 - val_mae: 50098.6602
Epoch 58/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - loss: 49514.1367 - mae: 49514.1367 - val_loss: 50101.4062 - val_mae: 50101.4062
Epoch 59/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - loss: 49508.8438 - mae: 49508.8438 - val_loss: 50094.4219 - val_mae: 50094.4219
Epoch 60/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49506.1367 - mae: 49506.1367 - val_loss: 50090.2695 - val_mae: 50090.2695
Epoch 61/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49500.1562 - mae: 49500.1562 - val_loss: 50088.7539 - val_mae: 50088.7539
Epoch 62/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 914us/step - loss: 49493.3672 - mae: 49493.3672 - val_loss: 50093.3945 - val_mae: 50093.3945
Epoch 63/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 895us/step - loss: 49491.5977 - mae: 49491.5977 - val_loss: 50092.2070 - val_mae: 50092.2070
Epoch 64/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - loss: 49485.4844 - mae: 49485.4844 - val_loss: 50094.6016 - val_mae: 50094.6016
Epoch 65/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 911us/step - loss: 49482.5508 - mae: 49482.5508 - val_loss: 50094.3984 - val_mae: 50094.3984
Epoch 66/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49479.5938 - mae: 49479.5938 - val_loss: 50101.6367 - val_mae: 50101.6367
Epoch 67/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49475.0000 - mae: 49475.0000 - val_loss: 50089.6602 - val_mae: 50089.6602
Epoch 68/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49471.7148 - mae: 49471.7148 - val_loss: 50090.0352 - val_mae: 50090.0352
Epoch 69/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49466.0664 - mae: 49466.0664 - val_loss: 50089.3945 - val_mae: 50089.3945
Epoch 70/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - loss: 49463.0703 - mae: 49463.0703 - val_loss: 50097.9219 - val_mae: 50097.9219
Epoch 71/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 987us/step - loss: 49456.0039 - mae: 49456.0039 - val_loss: 50086.8359 - val_mae: 50086.8359
Epoch 72/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 945us/step - loss: 49453.7852 - mae: 49453.7852 - val_loss: 50086.8281 - val_mae: 50086.8281
Epoch 73/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - loss: 49453.2305 - mae: 49453.2305 - val_loss: 50090.6172 - val_mae: 50090.6172
Epoch 74/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - loss: 49451.8281 - mae: 49451.8281 - val_loss: 50082.4570 - val_mae: 50082.4570
Epoch 75/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49443.2969 - mae: 49443.2969 - val_loss: 50094.4180 - val_mae: 50094.4180
Epoch 76/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 930us/step - loss: 49440.0156 - mae: 49440.0156 - val_loss: 50087.2539 - val_mae: 50087.2539
Epoch 77/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49442.2812 - mae: 49442.2812 - val_loss: 50077.8281 - val_mae: 50077.8281
Epoch 78/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 921us/step - loss: 49433.4727 - mae: 49433.4727 - val_loss: 50087.2305 - val_mae: 50087.2305
Epoch 79/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49432.9766 - mae: 49432.9766 - val_loss: 50086.0547 - val_mae: 50086.0547
Epoch 80/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49429.4102 - mae: 49429.4102 - val_loss: 50091.8320 - val_mae: 50091.8320
Epoch 81/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49425.4805 - mae: 49425.4805 - val_loss: 50089.5195 - val_mae: 50089.5195
Epoch 82/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49423.3828 - mae: 49423.3828 - val_loss: 50083.7852 - val_mae: 50083.7852
Epoch 83/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 973us/step - loss: 49422.1484 - mae: 49422.1484 - val_loss: 50076.2500 - val_mae: 50076.2500
Epoch 84/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49416.9766 - mae: 49416.9766 - val_loss: 50081.5859 - val_mae: 50081.5859
Epoch 85/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49416.5117 - mae: 49416.5117 - val_loss: 50090.4766 - val_mae: 50090.4766
Epoch 86/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49412.1445 - mae: 49412.1445 - val_loss: 50089.0000 - val_mae: 50089.0000
Epoch 87/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 977us/step - loss: 49410.7227 - mae: 49410.7227 - val_loss: 50089.2578 - val_mae: 50089.2578
Epoch 88/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49405.0938 - mae: 49405.0938 - val_loss: 50080.7227 - val_mae: 50080.7227
Epoch 89/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49402.5625 - mae: 49402.5625 - val_loss: 50072.3281 - val_mae: 50072.3281
Epoch 90/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 952us/step - loss: 49401.5273 - mae: 49401.5273 - val_loss: 50079.0898 - val_mae: 50079.0898
Epoch 91/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 940us/step - loss: 49396.2539 - mae: 49396.2539 - val_loss: 50076.3789 - val_mae: 50076.3789
Epoch 92/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 939us/step - loss: 49393.7578 - mae: 49393.7578 - val_loss: 50076.5234 - val_mae: 50076.5234
Epoch 93/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49393.9141 - mae: 49393.9141 - val_loss: 50088.1328 - val_mae: 50088.1328
Epoch 94/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49390.6797 - mae: 49390.6797 - val_loss: 50093.0586 - val_mae: 50093.0586
Epoch 95/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - loss: 49388.7969 - mae: 49388.7969 - val_loss: 50084.8672 - val_mae: 50084.8672
Epoch 96/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 959us/step - loss: 49383.6445 - mae: 49383.6445 - val_loss: 50088.2266 - val_mae: 50088.2266
Epoch 97/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 941us/step - loss: 49380.4648 - mae: 49380.4648 - val_loss: 50086.2891 - val_mae: 50086.2891
Epoch 98/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 923us/step - loss: 49377.3086 - mae: 49377.3086 - val_loss: 50085.0039 - val_mae: 50085.0039
Epoch 99/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - loss: 49378.5078 - mae: 49378.5078 - val_loss: 50092.1523 - val_mae: 50092.1523

In [19]:
%load_ext tensorboard

In [22]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6007 (pid 5131), started 0:00:04 ago. (Use '!kill 5131' to kill it.)

In [24]:
##evaluate model on the test data

test_loss,test_mae = model.evaluate(X_test,y_test)
print(f"Test MAE : {test_mae}")

79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 454us/step - loss: 50072.3281 - mae: 50072.3281
Test MAE : 50072.328125

In [25]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.